### ISSUE TITLE
Test https://solanalytic.massbit.io/

### ISSUE THREAD

**Issue by vuviettai** [massbitprotocol/sol-analytic#12]
1. [x] Block list
 - Url: https://solanalytic.massbit.io/blocks/
 - Current status: Open link and click refesh, content is not reloaded form server
 - Expected behavior: Auto reload content from server by period 60s, if user clicks button reload, timeout is clear and reload lastest data from server.
2. [x] Transaction list
- Url: https://solanalytic.massbit.io/transactions/
 - Current status: Open link and click refesh, content is not reloaded form server
 - Expected behavior: Auto reload content from server by period 60s, if user clicks button reload, timeout is clear and reload lastest data from server.
3. [x] Transaction detail
- Url: https://solanalytic.massbit.io/transactions/5DM4uN2gHgjs6hFyg6KXxqyWpo6nsqCRf4yCtPmi2G7GLKM8pX5jeH9sh1bpTe2W58G3oWGDwFpkEUEntzGgQh23
- Steps: 
    - Open transaction list: https://solanalytic.massbit.io/transactions/
    - Click to one transaction hash to open transaction detail page
- Current status: Detail page is empty\
- Expected behavior: Detail page is open with transaction detail

---
ETA: 0.5 day

**Comment by mison201** [comment]
Because Api get Transaction `5DM4uN2gHgjs6hFyg6KXxqyWpo6nsqCRf4yCtPmi2G7GLKM8pX5jeH9sh1bpTe2W58G3oWGDwFpkEUEntzGgQh23` is not found, detail page is empty
